spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}

chaos:
  monkey:
    enabled: true
    watcher:
      service: true
    assaults:
      latencyActive: true

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
